apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tgTest
  description: |
    This is a Test description, too.
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Test Chat
      url: https://test.com
  annotations:
    github.com/project-slug: tgau/backstage
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: library
  owner: tgau-person
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tgau-api
  description: An example API
spec:
  type: openapi
  lifecycle: experimental
  owner: tgau-person
  system: tgau-system
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: TGau API
      license:
        name: MIT
    servers:
      - url: http://api.gau.name/v1
    paths:
      /artists:
        get:
          summary: List all artists
